apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
commonLabels:
  deploy_type: dev
bases:
  - ../../../kustomize/base

resources:
  - service.yaml
  - namespace.yaml
patchesStrategicMerge:
  - patches/workload.yaml