apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
commonLabels:
  deploy_type: prod
bases:
  - ../../../kustomize/base

resources:
  - service.yaml
patchesStrategicMerge:
  - patches/workload.yaml
