---

apiVersion: v1
kind: Secret
metadata:
  name: flux-git-deploy
  namespace: flux-system
type: Opaque
data:
  username: YWxzYWhlZW0=
  password: Z2hwX0FxbDRyOTNXVDNNWnZoN01Mek51Y1BpRE5MbDltUzJURGtIbw==